LOONGSON: LoongArch port
Squashed commit of the following:

commit 06f00bc81c7d0dc3e83363fd2b00dd6b03f4d62a
Merge: 15f5afd71be3 eed263c8077e
Author: aoqi <aoqi@loongson.cn>
Date:   Thu Oct 17 10:41:06 2024 +0800

    Merge

commit 15f5afd71be34dd61b9044dff02e004eb2bb34b6
Author: loongson-jvm <jvm@loongson.cn>
Date:   Thu Oct 17 10:27:02 2024 +0800

    Update (2024.10.17)

    11541: Prevent load reorder of VarHandle::getOpaque
    34943: 8338748: [17u,21u] Test Disconnect.java compile error: cannot find symbol after JDK-8299813

commit 76487ad345f72808f2dbed45bde1fbe52f91f7b0
Merge: c6583c8c5cbd 33cd4b41b381
Author: aoqi <aoqi@loongson.cn>
Date:   Wed Oct 16 18:04:00 2024 +0800

    Merge

commit c6583c8c5cbd49c33df3dc3e65eb9644b8755bfc
Author: loongson-jvm <jvm@loongson.cn>
Date:   Wed Oct 16 18:02:45 2024 +0800

    Update (2024.10.16)

    34860: [MIPS] build with gtest failed after JDK-8300806

commit 6d0dc6b25f6441f3d37672ea377cc9c75e958693
Merge: 0389c6ca1b08 03cbfaa733bc
Author: aoqi <aoqi@loongson.cn>
Date:   Wed Oct 16 17:28:09 2024 +0800

    Merge

commit 0389c6ca1b08f91f75c63ed72edbe16abe2210c0
Merge: 00ca185ba7ea 833f65ecb304
Author: aoqi <aoqi@loongson.cn>
Date:   Fri Jul 26 14:48:30 2024 +0800

    Merge

commit 00ca185ba7eaf8a3bf9412bad9305fe742c3378c
Merge: 4cc0b3e97643 c1c901179e8e
Author: aoqi <aoqi@loongson.cn>
Date:   Fri Jul 26 14:47:58 2024 +0800

    Merge

commit 4cc0b3e97643ac46a8e64ea4f3c62510fe49e10a
Author: loongson-jvm <jvm@loongson.cn>
Date:   Fri Jul 26 11:32:26 2024 +0800

    Update (2024.07.26)

    33980: Fix generate__kernel_rem_pio2

commit c5070ec1c962df668c876c96554747da28c35520
Merge: c53840e66c90 c9d83d392f38
Author: aoqi <aoqi@loongson.cn>
Date:   Fri Jul 26 09:24:27 2024 +0800

    Merge

commit c53840e66c908f283ba8cf2b167cb3f5d68008fd
Author: loongson-jvm <jvm@loongson.cn>
Date:   Fri Apr 26 18:35:30 2024 +0800

    Update (2024.04.26, 2nd)

    34058: LA port of 8322122: Enhance generation of addresses

commit af76bcbea0b9c4b802af19ba09b062ef510e1d97
Merge: 38b11e8e0166 1c40f899c9c7
Author: aoqi <aoqi@loongson.cn>
Date:   Fri Apr 26 18:25:16 2024 +0800

    Merge

commit 38b11e8e016687f029cad4c183de4aaaf49020d0
Author: loongson-jvm <jvm@loongson.cn>
Date:   Fri Apr 26 18:24:13 2024 +0800

    Update (2024.04.26)

    33160: LA port of 8261837: SIGSEGV in ciVirtualCallTypeData::translate_from

commit a41749611bd86a21d5021378bc8b0cf6c9caa1f7
Merge: 202b0ef58d93 39c9e9d2bf82
Author: aoqi <aoqi@loongson.cn>
Date:   Fri Apr 26 18:07:56 2024 +0800

    Merge

commit 202b0ef58d9311f534f9bd10606e0e45accf92b7
Merge: 5f77562ba03d ca760c86642a
Author: aoqi <aoqi@loongson.cn>
Date:   Fri Jan 26 16:40:44 2024 +0800

    Merge

commit 5f77562ba03d1713d3615d84f8a3229a39258d41
Author: loongson-jvm <jvm@loongson.cn>
Date:   Fri Jan 26 16:39:46 2024 +0800

    Update (2024.01.26, 2nd)

    24527: Fix a typo for invokeinterface in #8604

commit fe193bcbc1cb971738db7fa2d38a9d69456a2c6c
Author: loongson-jvm <jvm@loongson.cn>
Date:   Fri Jan 26 16:29:44 2024 +0800

    Update (2024.01.26)

    29494: Fix assert(_succ != current) failed: invariant
    30985: Insert acqure membar for load-exclusive with acquire
    26386: Fix atomic ops with memory order relaxed
    28135: Add linux-loongarch64 to CheckedFeatures.notImplemented
    33199: GHA testing failed

commit a6ce2246d45bfb51c72d93e48dcf48cd6ad24917
Merge: 84bd3bf8f104 b78a848cc7ae
Author: aoqi <aoqi@loongson.cn>
Date:   Fri Jan 26 16:13:03 2024 +0800

    Merge

commit 84bd3bf8f104c294b595be579fa4268c5c83ed82
Merge: 99147f782457 9c16e89d2756
Author: aoqi <aoqi@loongson.cn>
Date:   Thu Dec 7 22:42:44 2023 +0800

    Merge

commit 99147f78245703b07fbbf35b7198521eada4cf2c
Author: loongson-jvm <jvm@loongson.cn>
Date:   Thu Dec 7 20:59:32 2023 +0800

    Update (2023.12.07, 2nd)

    32519: Fix for 31967 set default MaxGCPauseMillis
    31967: [G1GC] Set default MaxGCPauseMillis=150ms
    32564: MIPS port of 8284273: Early crashes in os::print_context on AArch64
    32563: MIPS port of 8283326: Implement SafeFetch statically
    32186: LA port of 8314020: Print instruction blocks in byte units
    31295: Provide information when hitting a HaltNode
    28314: Misc crash dump improvements
    28096: LA port of 8293851: hs_err should print more stack in hex dump
    26263: LA port of 8284273: Early crashes in os::print_context on AArch64
    32079: LA port of 8313796: AsyncGetCallTrace crash on unreadable interpreter method pointer
    30410: LA port of 8303154: Investigate and improve instruction cache flushing during compilation
    23671: MIPS/LA port of 8277417: C1 LIR instruction for load-klass
    25388: LA port of 8283326: Implement SafeFetch statically

commit 52397e8a10845dc42966971478c0c50a75330dff
Merge: e7efed5c455e dc00ae47d7af
Author: aoqi <aoqi@loongson.cn>
Date:   Thu Dec 7 18:25:10 2023 +0800

    Merge

commit e7efed5c455e2af269d45f1761fb8a22a0834b78
Author: loongson-jvm <jvm@loongson.cn>
Date:   Thu Dec 7 18:05:56 2023 +0800

    Update (2023.12.07)

    30457: Use membars when accessing volatile _thread_state
    32163: The size of is_wide_vector should be greater than 8 bytes

commit 983f139f47a778dcb225d3a514f5ca5f9f949e06
Merge: 0ca05554a068 3197a9b02992
Author: aoqi <aoqi@loongson.cn>
Date:   Mon Aug 14 19:28:14 2023 +0800

    Merge

commit 0ca05554a0681d353bc743c741cec776f2e9bf5e
Author: loongson-jvm <jvm@loongson.cn>
Date:   Mon Aug 14 19:24:05 2023 +0800

    Update (2023.08.14, 2nd)

    30943: LA port of 8303588: [JVMCI] make JVMCI source directories conform with standard layout
    22702: MIPS/LA port of 8252990: Intrinsify Unsafe.storeStoreFence

commit 1f64aa86dc7214e3587472b98886550f777c890f
Merge: d833eebe2384 0f531dacb878
Author: aoqi <aoqi@loongson.cn>
Date:   Mon Aug 14 17:52:34 2023 +0800

    Merge

commit d833eebe238495b3493dc760d56a5da4490118b7
Author: loongson-jvm <jvm@loongson.cn>
Date:   Mon Aug 14 17:49:18 2023 +0800

    Update (2023.08.14)

    30285: ArrayCopy: Align destination address
    27957: Mark stub code without alignment padding

commit cece1917fcfc054ec2d8e7db859536b2d19b208d
Author: loongson-jvm <jvm@loongson.cn>
Date:   Mon Jul 3 21:07:28 2023 +0800

    Update (2023.07.03)

    31006: Fix VectorInsert
    30358: Add support for ordering memory barriers
    9854: Implement cross modify fence

commit 2eceaca5eb843f2c040de99e82cd17a24b7167c1
Merge: f3b0a23f659e 22cdf79dce8b
Author: aoqi <aoqi@loongson.cn>
Date:   Wed May 17 14:31:52 2023 +0800

    Merge

commit f3b0a23f659eef01237010d69ea71d0aee9bf1a1
Author: loongson-jvm <jvm@loongson.cn>
Date:   Wed May 17 14:29:44 2023 +0800

    Update (2023.05.17)

    29453: Some cpu features use hwcap detect

commit 4d654249359c20b98708cb4c4c3866ea6d6657e7
Author: loongson-jvm <jvm@loongson.cn>
Date:   Fri Feb 24 09:17:04 2023 +0800

    Update (2023.02.23)

    29653: windows debug build failed
    29652: 8301397: [11u, 17u] Bump jtreg to fix issue with build JDK
    29655: ppc64le build failed
    23864: Fix caller saved fpu regset
    28680: [MIPS] Fix a typo in PosixSignals::pd_hotspot_signal_handler
    28678: Fix a typo in PosixSignals::pd_hotspot_signal_handler

commit 9f3079d058b332d7cec1c0b4568786aa8c84c363
Merge: d4dcc0bf7b8b 2fe42855c48c
Author: aoqi <aoqi@loongson.cn>
Date:   Tue Jan 31 19:07:27 2023 +0800

    Merge

commit d4dcc0bf7b8bca2f2a0095278bc573879726eb0f
Author: loongson-jvm <jvm@loongson.cn>
Date:   Tue Jan 31 16:17:39 2023 +0800

    Initial commit by Loongson

    A LoongArch64 port (template interpreter, C1 JIT compiler and C2 JIT compiler) and a MIPS64 port (template interpreter and C2 JIT compiler).

    Co-authored-by: Loongson JVM team